### ISSUE TITLE
Why does `count` perform query collection?

### ISSUE THREAD

**Issue by mingfang** [SoftInstigate/restheart#108]
According there https://softinstigate.atlassian.net/wiki/display/RH/Query+Documents#QueryDocuments-Counting, the count parameter queries the collection, twice. why?
The mongodb documentation clearly states that count() does not query at all, https://docs.mongodb.org/v3.0/reference/method/db.collection.count/.

Is there a way to execute the native mongodb version of count()?

**Comment by ujibang** [comment]
RESTHeart actually performs the count using the "nativa mongodb version of count()"

see ` public long getCollectionSize(final DBCollection coll, final Deque<String> filters)` in [CollectionDAO](https://github.com/SoftInstigate/restheart/blob/master/src/main/java/org/restheart/db/CollectionDAO.java)

so, in order to add the collection size to the response, it needs to execute two _queries_:

- colllection.count(filter)
- collection.find(filter).skip(page*pagesize).limit(pagesize)
