### ISSUE TITLE
Weaker concurrency with disabled If-Match check for updates

### ISSUE THREAD

**Issue by samfromlv** [SoftInstigate/restheart#112]
Restheart enforces strict concurrency protection model. To update a document you have to specify valid If-Match header with your PUT request, otherwise you will get 409 Conflict response. This approach assumes that you have read document before updating it. Its not the case for some systems where you sync data one way and concurrency is not the issue. 

I would suggest disabling 409 response it If-Match header was not sent. Another option to add configuration flag to control concurrency check behavior. 

Restheart version 1.1.6.

**Comment by ujibang** [comment]
Hi @samfromlv 

happy news, if you try the 2.0.0-beta-1 release it is already like that.

basically the behavior is on 2.x as follows:

- by default, ETag is required only for `DELETE /db` and `DELETE /db/coll`
- the default behavior can be set in configuration file, and specifiedl via _etagPolicy_ metadata (at db and collection level)
- if the client passes it via _If-Match_ header, it is checked anyway
- if the client passes the _checkEtag_ query parameter, it is checked anyway (this is useful if you want to make sure that a write operation does not result on updating an existing document, since all write operations have upsert semantic)

thanks for confirming this need.
