### ISSUE TITLE
Encrypted fields

### ISSUE THREAD

**Issue by jettdigital** [SoftInstigate/restheart#14]
In the API you have the rels meta-data for relationships, how difficult would it be to add another metadata tag that defines a document field as encrypted and use an Undertow handler to do the actual work? I think the encryption key should come from the command line, env variable, or config file. I'm working on a project that has data-encrypted-at-rest requirements.

Man there's so much I want to do on this project but I have zero time, you guys should offer like a restheart sponsorship product where a company can pay you to enhance restheart. It would become a revenue generating project and so up the priority on restheart enhancements.

**Comment by mkjsix** [comment]
I leave to my colleague to answer your first questions in details later, but it doesn't sound a lot of work to me (just thinking loud).

We are actually thinking about ways to finance the project, as we are facing increasing interest and it's becoming kind of a full-time job now :)

**Comment by jettdigital** [comment]
I know there's some Ruby code out there that does this, I'll see what i can
dig up and maybe try to hack something together.

On Wed, Jan 21, 2015 at 11:58 AM, Maurizio Turatti <notifications@github.com

**Comment by ujibang** [comment]
This is feasible indeed: it should be quite easy to implement following this approach:

* as you said, model the metadata like the [refs](https://github.com/SoftInstigate/restheart/blob/develop/src/main/java/org/restheart/hal/metadata/Relationship.java) 
* in PutCollectionHandler and PatchCollectionHandler make sure to check the metadata format (check how this is done for reals) so that we are sure that the definition conform to the defined format
* a special handler can be piped in the GET request logic to encrypt the properties specified by the collection metadata, with an algorithm and key defined in the configuration file
