### ISSUE TITLE
Possible to grab the byte array when submitting to a collection using GridFS?

### ISSUE THREAD

**Issue by Skyark112** [SoftInstigate/restheart#171]
Hey,

I'm using version 2.0.2 was wondering if there was a way to use a transformer to grab a byte array of a document passed in to be stored into GridFS. 

To clarify, right now, the contentToTransform being passed into a transformer when I store an image is:

``{filename=testpic.png, contentType=image/png}``

Is it possible to get the byte array of that png file into the contentToTransform and maybe make modifications to it before it is chunked and stored?

**Comment by ujibang** [comment]
Hi @Skyark112 

if you have control on the client side, better to go directly with a multi-part POST to the file bucket (e.g. /db/bucket.files), refer to [GridFS](https://softinstigate.atlassian.net/wiki/x/RoCw) on the documentation. 

In this case you pass the binary data in the `file` part in and the metadata in the `properties` part, eg with curl:

```
curl -v -u user:password -X POST -F 'properties={"name":"Maurizio", "surname":"Turatti"}' -F "file=@picture.png;filename=picture.png" 127.0.0.1:8080/testdb/mybucket.files
```

otherwise I suggest to develop a custom [Application Logic Handler](https://softinstigate.atlassian.net/wiki/x/IoCw). The transformer won't apply since write requests to file buckets (GridFS) expect a multi-part request and will fail when POSTing plain json.

**Comment by Skyark112** [comment]
Cool thanks, I was actually trying to use the multi-part POST when I realized that I had to actually change the binary data before it was chunked and stored. 

Looks like I'll be writing a custom logic handler for this.

To clarify, the client would have to hit an entirely new URI? For example if I wanted to make a logic handler to modify a file sent in, I would write a logic handler and call it, say, FileModify.  

I would add it to the config file like this
```application-logic-mounts:
    - what: path.to.my.handler.FileModify
      where: /modify
      secured: true```

The resulting URI that the client would have to use would be something like:
```http -a <user>:<pass> POST <IP>:<PORT>/_logic/convert <metadata>```

And I would get the metadata the client passed in through the context?

**Comment by ujibang** [comment]
Hi @Skyark112 

sorry for late response but we were busy releasing 3.0

I checked it and I realized that the application logic chain of handlers misses the BodyInjectorHandler which is in charge of the setting the content in the RequestContext.

I just pushed a fix for this. Can you check it with your case?

I also modified the PingHandler to send the content in the response

```
POST /_logic/ping {"a": 1 }

response => {"a": 1}
```

**Comment by Skyark112** [comment]
Sure, let me check it out. Thanks for looking into this! 
Is this fix for my version?

**Comment by Skyark112** [comment]
Thanks! That was a better approach than mine. Closing the ticket.
