### ISSUE TITLE
data version management

### ISSUE THREAD

**Issue by mohankv** [SoftInstigate/restheart#175]
I have a requirement to manage the versions of documents for certain collections. When a document is updated, previous values (history) should be embedded in the same document or preferably created in a separate versioned document that can be referred in the current updated document. What’s the easy way to accomplish this?

**Comment by ujibang** [comment]
Hi @mohankv 

my suggestion is to use an [hook](https://softinstigate.atlassian.net/wiki/x/EgAtAQ).

with an hook you can get the OperationResult which encapsulates (for write requests) both the new and old data.

```
boolean hook(
            HttpServerExchange exchange,
            RequestContext context,
            BsonValue args) {
      OperationResult res = context.getDbOperationResult();
      BsonDocument oldData = res.getOldData();

      BsonValue id = oldData.remove("_id");
      oldData.append("refId", id);
      oldData.append("timestamp", new BsonDateTime(System.currentTimeMillis()));

      // now you can store the oldData in a versions collection. 
      // the refId property is the reference to the versioned document
}
```

make sure to apply the hook only on write request, implementing the `doesSupportRequests(RequestContext context)` method accordingly (see docs for an example)

you can also define an inverse ONE_TO_MANY [relationship](https://softinstigate.atlassian.net/wiki/x/iYCM) between your collection a the versions collection. so that you'll have a versions link automatically embedded in you docs.

**Comment by mohankv** [comment]
Great! Thanks @ujibang.
