### ISSUE TITLE
Issue with Response Transformers in v 3.0.0

### ISSUE THREAD

**Issue by Skyark112** [SoftInstigate/restheart#178]
Hey,

I'm not sure if something was changed in 3.0.0, but when I converted my transformer code from 2.0.1 to match 3.0.0 specifications, I had problems with RestHEART going into my Response Transformer because it seems to go into my Request Transformer first. 

```
http -a <user>:<pass> PUT 127.0.0.1:8080/testdb/testcol3 rts:='[{"name":"changeFormat","phase":"REQUEST","scope":"CHILDREN"},{"name":"addField","phase":"RESPONSE","scope":"CHILDREN"}]'
```

I was trying to do something like http -a <user>:<pass> GET 127.0.0.1:8080/testdb/testcol3 when running 3.0.0 and I get caught by an error in my changeFormat transformer. However, when I change RestHEART back to 2.0.1 it works perfectly. 

Not sure I'm doing something wrong. Help would be appreciated! Thanks for everything so far.

**Comment by ujibang** [comment]
Hi @Skyark112 

the main difference between 3.x and 2.x is that request and response transformers always apply despite the request type.

in 2.x response transformers apply only to GET requests and request transformers only to write requests (PUT, POST and PATCH).

in order to cover some use cases transformers now are always invoked. for instance, a response transformers can now apply to write request to make a PUT/POST sending back some result body (an example is [WriteResultTransformer](https://github.com/SoftInstigate/restheart/blob/5536dda7d228c4d2b04fefac82db9b2a5b48995e/src/main/java/org/restheart/hal/metadata/singletons/WriteResultTransformer.java) that sends back the operation result (old and new data).

What you have to do is just checking if your transformers should apply. So for example at the beginning of your `transform()` methods you can check if it is actually a document write request.

in the code that follows the transfomer is applies to

- PUT document `PUT /db/coll/docid`
- PATCH document `PATCH /db/coll/docid`
- POST collection `POST /db/coll (both a single doc or an array of docs)
- bulk PATCH documents `PATCH /db/coll/*`

```
@Override
    public void transform(
            final HttpServerExchange exchange,
            final RequestContext context,
            BsonValue contentToTransform,
            final BsonValue args) {
        if (!doesApply(context) || contentToTransform == null) {
            // nothing to do
            return;
        }

        // transform logic follows
}

/**
     *
     * @param context
     * @returns true if request is PUT/PATCH document or POST collection
     */
private boolean doesApply(RequestContext context) {
        return ( // PUT|PATCH /db/coll/docid
                (context.getType() == TYPE.DOCUMENT
                && (context.getMethod() == RequestContext.METHOD.PATCH
                || context.getMethod() == RequestContext.METHOD.PUT))
                // POST /db/coll { <doc> } and POST /db/coll [ { <doc> }, { <doc> } ]
                || ((context.getType() == TYPE.COLLECTION)
                && (context.getMethod() == RequestContext.METHOD.POST))
                // PATCH /db/coll/*
                || ((context.getType() == TYPE.BULK_DOCUMENTS)
                && context.getMethod() == RequestContext.METHOD.PATCH));
    }
```

**Comment by Skyark112** [comment]
This solved it! Sorry forgot to close it a while back.

**Comment by mkjsix** [comment]
@Skyark112 no problem, we're glad you have solved your issue!
