### ISSUE TITLE
Docker version: The restheart.yml configuration file is not coherent with the jar file

### ISSUE THREAD

**Issue by osaiz** [SoftInstigate/restheart#281]
In the docker version, the restheart.yml config file, the paths of the metadata-named-singletons are not correct. This happens for checkers, transformers and hooks.

Let's see checkers as an example: 

Should-be:
    - group: checkers
      interface: org.restheart.metadata.checkers.Checker
      singletons:
        - name: jsonSchema
          class: org.restheart.metadata.checkers.JsonSchemaChecker
        - name: checkContent
          class: org.restheart.metadata.checkers.JsonPathConditionsChecker
        - name: checkContentSize
          class: org.restheart.metadata.checkers.ContentSizeChecker

It is:
    - group: checkers
      interface: org.restheart.hal.metadata.singletons.Checker
      singletons:
        - name: jsonSchema
          class: org.restheart.hal.metadata.singletons.JsonSchemaChecker
        - name: checkContent
          class: org.restheart.hal.metadata.singletons.JsonPathConditionsChecker
        - name: checkContentSize
          class: org.restheart.hal.metadata.singletons.ContentSizeChecker

**Comment by mkjsix** [comment]
Thank you @osaiz, I have spotted also another couple of similar problems with obsolete package references in other sections of the `restheart.yml` file for Docker. Everything should be fixed in the following releases:

- master (3.4.0-SNAPSHOT with tag `latest`)
- 3.3.1
- 3.2.4

See https://hub.docker.com/r/softinstigate/restheart/tags/
