### ISSUE TITLE
100% LDAP Access Manager

### ISSUE THREAD

**Issue by Bccorb** [SoftInstigate/restheart#302]
## Expected Behavior
The ADAccessManager should work with systems that are pure LDAP or there should be an LDAP access manager.

## Current Behavior
ADAccessManager should work in a 100% LDAP enviroment or it should possess and LDAP only access method

## Context
I have an LDAP server that I am trying to authenticate against utilizing Restheart

## Environment
Centos 7
RestHeart latest
Mongo 3.4

## Steps to Reproduce
1. Have an LDAP server for authentication
2. Use the ADAccessManager
3. Fails on authenticating because no AD components

**Comment by mkjsix** [comment]
Hi @Bccorb,
Thank you for your report. The `ADIdentityManager` was an external contribution and so far we neither have had the need to access an LDAP by ourselves, nor we have received enough requests about it from the community. We gladly accept PRs, otherwise we can evaluate to include something in our roadmap in two cases:

1. There are multiple incoming requests from the community about a specific feature;
2. A company is willing to directly sponsor and pay for the development effort.

If you think you can contribute an implementation by yourself we'll be happy to assist you in merging the PR. We request at least a set of regression tests and some documentation, so that we can include the contribution in our continuous integration pipeline and in the documentation portal. In this specific case, we'd need guidance on how to setup a basic testing LDAP environment (for example, we could start and populate a dockerized LDAP instance so that it could run within our end-to-end Travis-CI automatic build process).

Note that most of our team is on vacation these days, so unfortunately we cannot assure prompt replies anyway.
