### ISSUE TITLE
Handle ENV variables in RH configuration

### ISSUE THREAD

**Issue by johnnywiller** [SoftInstigate/restheart#313]
## Expected Behavior
It would be great if RH support evaluation of environment variables in the configuration files.
`restheart.yml` and `security.yml`

## Current Behavior
It's not supported

## Context
I'm trying to use configuration parameters coming from `docker-compose` files in the form of environment vars, like JWT secrets, Mongo url connection, port to RH listen to, etc.  

## Environment
Don't apply.

**Comment by mkjsix** [comment]
Hi @johnnywiller,
I think that's indeed a very good idea, I'm actually having similar needs. It would allow to write parametric configuration files. I'll surely have a look in the following days.

**Comment by mkjsix** [comment]
In RESTHeart 3.6.0-SNAPSHOT We have implemented the possibility to pass an optional properties file as a startup parameter or as a environment variable:

For example, look at files in `etc/` folder.

The `dev.properties` file contains a single line:

```properties
mongouri = mongodb://127.0.0.1
```

While the `restheart-dev.yml` contains a the `mongouri ` parameter:

```yaml
mongo-uri: {{mongouri}}
```
We are using the [Mustache.java](https://github.com/spullara/mustache.java) library, which is a derivative of mustache.js.

After building the source code with `mvn clean package`, to start RESTHeart with this properties file you can use the `--envfile` command line parameter:

```
java -Dfile.encoding=UTF-8 -server -jar target/restheart.jar etc/restheart-dev.yml --envfile etc/dev.properties
```

Alternatively you could pass the envifile path via the `RESTHEART_ENVFILE` environment variable:

```bash
$ export RESTHEART_ENVFILE=etc/dev.properties
$ java -Dfile.encoding=UTF-8 -server -jar target/restheart.jar etc/restheart-dev.yml
```

This approach allows to put all the variables into a single file.

Of course, in the future we could also think about extending this by adding the capability to read environment variables directly instead of reading a properties file, if there are suitable use cases. 

By the way, we added a better support for command line parameters by including the JCommander library. For example, here is the `--help` parameter in action:

```bash
$ java -jar target/restheart.jar --help
Usage: java -Dfile.encoding=UTF-8 -jar -server restheart.jar [options] 
      <Configuration file>
  Options:
    --envFile, --envfile, -e
      Environment file name
    --fork
      Fork the process
      Default: false
    --help, -?
      This help message
```

**Comment by mkjsix** [comment]
I added the possibility to override any **primitive type parameter** (String, Integer, Long, Boolean) in `restheart.yml` with an environment variable. For example, the parameter `mongo-uri` in the yaml file can be overridden by exporting a `MONGO_URI` environment variable:

```bash
$ export MONGO_URI="mongodb://127.0.0.1"
```

You'll see the following log entry at the very beginning of RH's log:

```
[main] WARN  org.restheart.Configuration - >>> Overriding parameter 'mongo-uri' with environment value 'MONGO_URI=mongodb://127.0.0.1'
```

The rule is pretty simple: a shell environment variable is equivalent to a yaml parameter but it's uppercase and '-' (dash) are replaced with '_' (underscore).

ATM this environment variables replacement doesn't work with YAML structured data in configuration files, like arrays or maps. You must use properties files and mustache syntax for that.

TODO: add this to `security.yml`. I'll probably do that in the following days.

**Comment by johnnywiller** [comment]
Cool, thanks very much for adding this

**Comment by mkjsix** [comment]
We've added the following documentation: https://restheart.org/learn/configuration-file/
RESTHeart 3.6.0 is planned to be released within the end of this year.
