### ISSUE TITLE
Integration with Mongoose

### ISSUE THREAD

**Issue by earl-jann** [SoftInstigate/restheart#39]
Hi!

Sorry, I'm just new in learning mongodb and node. I'd just want to ask if integration with mongoose is feasible? Im thinking that the rest calls pass through mongoose for schema validations first.

Thanks!

**Comment by mkjsix** [comment]
Hi,

RESTHeart is entirely written in Java, so nothing to do with either nodejs or Mongoose!

Regards

**Comment by thinw002** [comment]
I could see the mongoose schema (or JSON Schema) being leveraged to make RestHeart schema-aware in the future like other frameworks.

**Comment by ujibang** [comment]
Hi @thinw002, RESTHeart does support JSON Schema: https://restheart.org/docs/json-schema-validation

**Comment by mkjsix** [comment]
@thinw002 of course Mongoose has a much broader scope than basic JSON schema validation, as it is a fully fledged object modeling tool. But Mongoose works client-side, by creating objects on the nodejs client which match the BSON data model it creates on the database side. RESTHeart, on the other hand, is a server-side only technology where you are free to use the client tech you want, providing that it can handles basic HTTP calls.
IMO to go the object modeling route one would need a Mongoose-like client library which handles REST endpoints instead of going directly to the database. It would be an interesting exercise to imagine that, in the past we where thinking about creating a SDK for RESTHeart, but that has never moved into our top priority, mostly because a proper SDK for RESTHeart should be multi-language (we don't mandate any specific client-side programming language) and would require a lot of resources to develop and maintain it.
