### ISSUE TITLE
[FEATURE REQUEST] Multi arch docker image 

### ISSUE THREAD

**Issue by ionutz89** [SoftInstigate/restheart#407]
It will be great if you can build the docker image as `multi-arch`. At the moment it is only for `amd64`.

Very useful this tool on Raspberry Pi 4 on `arm64`

**Comment by mkjsix** [comment]
That's interesting but we don't have experience with multi-arch docker images, could you point us toward some docs and examples?

**Comment by ionutz89** [comment]
I created this [repo](https://github.com/homeall/restheart-multi-arch) as an example.

It is super easy if you will GithubActions and push to docker hub.

I changed a bit your Dockerfile. Please have a look at the GithubAction file.

**Comment by mkjsix** [comment]
Ok tanks, I'll have a look into it. We need to be careful because we have several customers running RESTHeart with Docker in production and we don't want to break anything. We'll do some test in the following days.

Meanwhile beware that yesterday (27 March) we have just moved to JDK 16, so if you use SNAPSHOT releases from master branch you need to upgrade (See the new [Dockerfile](https://github.com/SoftInstigate/restheart/blob/master/core/Dockerfile)). Nothing has changed if you are still building from stable releases (5.3.x branch).

**Comment by ionutz89** [comment]
Thank you for let me know about the `JDK 16 version`. 

I updated and it works as expected.  🍻 👍

**Comment by mkjsix** [comment]
Hi @ionutz89 
We've published an experimental RESTHeart v6.0 multi-arch build in our restheart-snapshot docker repo.

https://hub.docker.com/layers/softinstigate/restheart-snapshot/latest/images/sha256-2386dbe6227a3e92a78fa634f18e6dd2aa5d948dd0b0f11d94715eca578466d9?context=repo 

Do you mind doing a `docker pull softinstigate/restheart-snapshot:latest` and give it a try?

It's built for linux/amd64, linux/arm64, linux/arm/v7 architectures, could you suggest additional architectures which might be useful?

**Comment by mkjsix** [comment]
We have now integrated the multi-arch builds in our build process, so you can pull the latest stable 6.0.2  release as well:

`docker pull softinstigate/restheart:latest` or `docker pull softinstigate/restheart:6.0.2`

**Comment by mkjsix** [comment]
I'm closing this issue, please re-open in case of further comments.

**Comment by ionutz89** [comment]
It works as expected. Thank you so much for your help. 👏
