### ISSUE TITLE
Connection to RESTHeart without typing your credentials inside of the command

### ISSUE THREAD

**Issue by orkhanalizade** [SoftInstigate/restheart#43]
In documentation writes that I must include my credentials inside of the command:

http PUT 127.0.0.1:8080/myfirstdb -a username:password

But it's not securely to use my credentials inside of the command. Can I connect, authorize, with the credentials from the file based Identity Manager configuration?

**Comment by mkjsix** [comment]
If you truly want security you **must** exchange information via SSL, there are no other ways.
So you can either activate SSL within RESTHeart or you can put a secure reverse proxy in front of it (Nginx or Apache).
For the first option:
 * https://softinstigate.atlassian.net/wiki/display/RH/5.+Advanced+Configuration#id-5.AdvancedConfiguration-SSL
 * https://softinstigate.atlassian.net/wiki/display/RH/5.+Advanced+Configuration#id-5.AdvancedConfiguration-Security

(please note that we are slowly moving the documentation to Confluence)

For our internal projects we use Nginx because it is much easier to configure, but that's up to you.

**Comment by orkhanalizade** [comment]
But in the case that if I'll send my credentials via SSL, are my
credentials encrypting and/or can other people find/see my credentials?

ср, 12 авг. 2015 г. в 12:21, Maurizio Turatti <notifications@github.com>:

**Comment by mkjsix** [comment]
In that case you are connecting to a HTTPS URL via SSL and it's exactly like exchanging information with a secure Web server via a browser, nothing less and nothing more. Of course, you should use a self-signed certificate only for development or limited internal usage, for production deployment on a public server you must buy a real SSL certificate from a verified certificate authority (your Internet provider might be one of those, but there are plenty).
